"""
Lean 2.0 Deep Checklist Migration - 60 items (12 per dimension)
Replaces the original 31 items with comprehensive, fastener-industry-specific questions.
Each item has detailed L1-L5 descriptions with concrete examples.
"""
import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), 'data', 'leanops.db')

def migrate():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Clear existing data
    c.execute("DELETE FROM lean20_checklist_items")

    # ============================================================
    # OPERATIONS (O) - 12 items
    # ============================================================
    o_items = [
        ('O01', '5S & Visual Management', 0.10,
         'No 5S practice; workplace disorganized; tools/items cannot be found; no visual controls',
         '5S started in some areas; basic visual boards exist but not updated regularly; red-tag events occasional',
         '5S maintained across all areas; visual management comprehensive (shadow boards, floor markings, Andon lights); Gemba board active with daily updates',
         '5S is embedded culture; visual management drives real-time decisions; autonomous audit teams; cross-area benchmarking',
         '5S self-sustaining and continuously improving; visual innovation (AR/AI-assisted); industry benchmark facility'),
        ('O02', 'Standard Work & SOP', 0.10,
         'No standard work docs; methods vary by operator; tribal knowledge only; high variability',
         'Some SOPs exist but outdated; execution inconsistent; no regular review cycle; operators not involved in creation',
         'SOPs complete & current for all key processes; execution consistent; regular review cycle (quarterly); operators contribute updates',
         'SOPs continuously improved via operator feedback; best-practice sharing across lines; video SOPs for complex tasks',
         'Standard work as innovation platform; self-evolving with AI-assisted updates; industry reference for work standardization'),
        ('O03', 'TPM & Equipment OEE', 0.09,
         'Breakdown maintenance only; no PM plan; OEE unknown or <55%; no equipment loss tracking',
         'Basic PM started; OEE 55-65%; autonomous maintenance (AM) awareness emerging; MTBF tracked for critical equipment',
         'TPM system running; OEE 70-80%; AM participation >60%; equipment loss analysis (Six Big Losses) standard practice',
         'Predictive maintenance active; OEE 80-85%; AM >80%; zero breakdown target for critical assets; equipment improvement Kaizen',
         'Autonomous maintenance culture; OEE >90%; world-class reliability; equipment data feeds digital twin'),
        ('O04', 'Process Quality & SPC', 0.09,
         'End-of-line inspection only; no process control; defect rate >500 PPM; quality = inspection',
         'SPC started at key stations; basic quality tools (7 QC tools); COPQ tracked; reaction-based quality',
         'SPC widespread; process control dominant; 8D/A3 for problem solving; defect rate <100 PPM',
         'Zero-defect culture; Six Sigma projects active (DMAIC); quality cost <2% of revenue; preventive quality systems',
         'Six Sigma level (<=3.4 PPM); quality as competitive advantage; AI-assisted process optimization; zero escapes'),
        ('O05', 'Flow, Pull & Kanban', 0.08,
         'Push production; high WIP between stations; long lead times; no pull signals; batch processing',
         'Kanban piloted in 1-2 lines; WIP reduction started; some cellular layout; lead time reduced 15%+',
         'Pull system running in key value streams; WIP controlled via Kanban; lead time reduced 30%+; takt time managed',
         'End-to-end pull; Heijunka leveling; JIT delivery to key customers; continuous flow in cellular lines',
         'Fully synchronized value stream; demand-driven pull; zero-waste flow; reconfigurable cells for product mix'),
        ('O06', 'Quick Changeover (SMED)', 0.07,
         'Long changeovers (>60min); no changeover reduction effort; high batch sizes to compensate',
         'SMED started; changeover time 30-60min; internal/external separation begun; quick-change fixtures piloted',
         'SMED standard practice; changeover <15min for most products; single-minute die change; standardized setup procedures',
         'Near-zero changeover (<5min); one-touch setup; changeover as competitive advantage; mixed-model capability',
         'Instant changeover; reconfigurable tooling; changeover eliminated via flexible manufacturing systems'),
        ('O07', 'Problem Solving & Kaizen', 0.07,
         'Firefighting culture; no structured approach; problems recur; no root cause analysis',
         'Basic 5-Why and fishbone usage; some A3 reports; root cause analysis occasional; Kaizen events 1-2/quarter',
         'A3/8D standard practice; PDCA cycle embedded; countermeasures verified and standardized; Kaizen events monthly',
         'Data-driven problem solving; predictive analytics for recurrence prevention; cross-functional Kaizen teams; employee-led',
         'Self-healing systems; AI-assisted root cause analysis; organizational learning loop; problems drive systemic improvement'),
        ('O08', 'Supply Chain Integration', 0.07,
         'No supplier collaboration; adversarial relationships; high inventory buffers; no shared data',
         'Basic supplier evaluation; safety stock for top-10 items; some communication; annual supplier reviews',
         'Supplier scorecard active; VMI pilots with key suppliers; joint improvement projects; shared forecasts',
         'Supplier lean coaching; JIT supply for critical items; risk-sharing partnerships; integrated planning systems',
         'Extended lean enterprise; ecosystem optimization; value network design; AI-driven supply orchestration'),
        ('O09', 'Inventory Management', 0.06,
         'Excessive inventory; no ABC classification; manual tracking; high carrying costs; frequent stockouts of critical items',
         'ABC classification done; basic reorder points set; cycle counting started; inventory turns tracked',
         'Inventory optimization active; safety stock calculated statistically; turns improved 30%+; FIFO enforced',
         'Dynamic inventory AI; demand-driven replenishment; inventory as strategic buffer (not waste); near-zero excess',
         'Autonomous inventory management; AI-predictive stocking; inventory cost minimized while service level maximized'),
        ('O10', 'Delivery Performance', 0.06,
         'On-time delivery <80%; no delivery tracking; frequent expediting; customer complaints about delivery',
         'OTD 80-90%; basic delivery tracking; lead time communication to customers; root cause for late deliveries tracked',
         'OTD 90-95%; real-time delivery tracking; proactive delay notification; delivery improvement Kaizen',
         'OTD 95-99%; predictive delivery management; delivery as competitive advantage; VMI/consignment for key customers',
         'OTD >99%; zero-late delivery culture; delivery excellence as customer promise; AI-optimized logistics'),
        ('O11', 'Cost Management & Waste Reduction', 0.06,
         'No systematic cost tracking; waste not measured; labor cost as % of revenue unknown',
         'Basic cost tracking by product line; 7 wastes identified; cost reduction targets set annually',
         'Activity-based costing; waste quantified in $; cost reduction 5-10% YoY; value stream cost analysis',
         'Real-time cost monitoring; waste elimination AI-assisted; target costing for new products; cost leadership position',
         'Cost transparency at all levels; zero-waste culture; cost as strategic weapon; lean accounting standard'),
        ('O12', 'Safety & Ergonomics', 0.06,
         'Reactive safety; no safety management system; ergonomic risks unaddressed; LTIR above industry average',
         'Basic safety program; incident tracking; PPE compliance; ergonomic assessment started for high-risk roles',
         'Behavior-based safety; near-miss reporting active; ergonomic improvements implemented; LTIR below industry average',
         'Safety culture embedded; zero-incident target; proactive hazard elimination; ergonomic design for all workstations',
         'Industry-leading safety; safety as core value; AI-assisted hazard prediction; employee wellbeing integrated'),
    ]

    # ============================================================
    # DIGITAL (D) - 12 items
    # ============================================================
    d_items = [
        ('D01', 'Production Data Collection', 0.09,
         'Paper records only; manual data entry; no real-time data; data accuracy <70%',
         'MES/ERP deployed for key processes; electronic records; basic data validation; 80% accuracy',
         'IoT data collection from equipment; automated data capture; real-time dashboards; >95% accuracy',
         'AI-driven data quality assurance; edge computing for real-time processing; digital twin data feeds',
         'Autonomous data ecosystem; self-validating data pipelines; AI-curated insights; zero manual entry'),
        ('D02', 'Process Visibility & Transparency', 0.08,
         'No production visibility; status unknown until end-of-line; decisions based on gut feel',
         'Electronic Kanban; production status boards; basic tracking; shift-end reports available',
         'Real-time OEE monitoring; SPC auto-alerts; Andon system; digital production board visible to all',
         'Digital twin for key processes; what-if simulation; AI anomaly detection; predictive alerts',
         'Full digital twin; real-time optimization; autonomous scheduling; complete value stream transparency'),
        ('D03', 'Quality Digitization & Traceability', 0.08,
         'Manual inspection only; paper records; no traceability; defects found at customer',
         'Digital inspection records; SPC software; basic traceability by batch; defect data digitized',
         'Automated inspection data collection; SPC auto-monitoring; full lot traceability; defect rate <100 PPM',
         'AI visual inspection (<100ms inference); predictive quality models; ML defect classification; zero escapes',
         'Zero-defect AI system; self-adjusting process parameters; digital quality passport per product; quality blockchain'),
        ('D04', 'Maintenance Digitization (CMMS)', 0.07,
         'Paper maintenance logs; breakdown-only maintenance; no data analysis; spare parts unknown',
         'CMMS deployed; PM scheduled digitally; MTBF/MTTR tracked; spare parts inventory digitized',
         'Condition monitoring (vibration/temperature/pressure); predictive maintenance models; digital work orders',
         'AI predictive maintenance; remaining useful life prediction; digital twin for asset health; prescriptive maintenance',
         'Self-healing equipment; AI autonomous maintenance scheduling; zero unplanned downtime; maintenance as value-add'),
        ('D05', 'Digital Decision Support', 0.07,
         'Decisions based on experience; no data-driven culture; reports are static and outdated',
         'BI dashboards for management; basic KPI reporting; weekly data review meetings; some drill-down capability',
         'Automated KPI dashboards; drill-down analytics; data-driven daily meetings; exception-based management',
         'AI decision support; scenario simulation; prescriptive recommendations; real-time decision intelligence',
         'Autonomous decision systems; AI-driven optimization; human-AI collaborative strategic decisions'),
        ('D06', 'Digital Culture & Literacy', 0.06,
         'Digital resistance; low IT literacy; paper preference; no digital training program',
         'Basic digital training; some digital champions; mixed adoption; leadership supports digital transformation',
         'Digital literacy programs for all levels; data-driven mindset; digital Kaizen events; change management active',
         'Digital innovation culture; citizen developers; AI-augmented workforce; digital transformation roadmap executing',
         'Digital-native organization; continuous digital evolution; industry digital leader; digital talent magnet'),
        ('D07', 'ERP/MES Integration', 0.06,
         'Standalone systems; no integration; data silos; double data entry; information delays',
         'Basic ERP-MES interface; some automated data flow; key processes connected; single source of truth emerging',
         'Full ERP-MES integration; real-time data flow; automated reporting; supply chain visibility',
         'Industry 4.0 architecture; API-first integration; real-time supply chain orchestration; cloud-native platform',
         'Autonomous operations platform; AI-orchestrated systems; zero integration friction; ecosystem connectivity'),
        ('D08', 'IoT & Connectivity', 0.06,
         'No IoT sensors; equipment not connected; no real-time monitoring; manual data collection only',
         'IoT sensors on critical equipment; basic connectivity; some real-time dashboards; pilot projects active',
         'IoT widespread across production; edge gateways; real-time monitoring of OEE/quality/safety; data lake',
         '5G-enabled IoT; digital twin real-time feeds; AI edge computing; autonomous process adjustment',
         'Fully connected factory; ubiquitous sensing; IoT as infrastructure; self-optimizing connected systems'),
        ('D09', 'Cybersecurity & Data Protection', 0.06,
         'No cybersecurity measures; no data backup strategy; high vulnerability; no incident response plan',
         'Basic firewall & antivirus; regular backups; IT security policy written; access controls basic',
         'IEC 62443 compliance; OT/IT segmentation; incident response team; tested disaster recovery; security training',
         'Zero-trust architecture; AI threat detection; cyber resilience testing; <1h recovery; security operations center',
         'Self-healing IT/OT security; quantum-ready encryption; cyber resilience benchmark; security as competitive advantage'),
        ('D10', 'AI & Machine Learning', 0.05,
         'No AI/ML usage; no data science capability; decisions purely human-driven',
         'AI pilot projects (quality inspection or demand forecasting); basic ML models; data science skills developing',
         'AI deployed in 2-3 production processes; ML models in production; A/B testing culture; measurable ROI',
         'AI integrated across value stream; deep learning for quality/predictive maintenance; AI-driven scheduling',
         'AI-native manufacturing; autonomous AI systems; human-AI collaboration standard; AI as core competency'),
        ('D11', 'Digital Customer Interface', 0.05,
         'Customer orders via phone/email only; no digital portal; order status unknown to customers',
         'Customer portal for order placement; basic order tracking; email notifications; EDI with key customers',
         'Real-time customer portal; order configurator; delivery tracking; API integration with customer systems',
         'Digital customer experience; self-service platform; AI-powered order promising; real-time supply chain visibility',
         'Seamless digital customer journey; platform-based customer integration; real-time collaborative planning'),
        ('D12', 'Data Governance & Analytics', 0.05,
         'No data governance; inconsistent data definitions; no analytics capability; data quality unknown',
         'Basic data governance policy; key metrics defined; data quality monitoring started; analytics team forming',
         'Data governance framework enforced; data catalog; self-service analytics; data quality >95%; data literacy program',
         'AI-assisted data governance; automated data quality; advanced analytics (descriptive/predictive/prescriptive)',
         'Autonomous data management; data as strategic asset; AI-driven insights; data monetization explored'),
    ]

    # ============================================================
    # GREEN (G) - 12 items
    # ============================================================
    g_items = [
        ('G01', 'Energy Management & Efficiency', 0.09,
         'No energy tracking; only pay bills; no efficiency awareness; energy cost unknown',
         'Energy metering started for major equipment; basic targets; annual energy audit; some monitoring',
         'Process-level energy monitoring; ISO 50001 foundation; energy Kaizen events; consumption reduced 15%+',
         'Energy management system (ISO 50001 certified); real-time optimization; green electricity >30%; smart grid participation',
         'Carbon-neutral energy; 100% renewable; energy-positive operations; energy excellence as brand differentiator'),
        ('G02', 'Carbon Footprint & CBAM Compliance', 0.09,
         'No carbon data; no emission awareness; CBAM unprepared; product carbon footprint unknown',
         'Scope 1+2 emissions calculated; basic carbon inventory; CBAM awareness training started; annual report',
         'Product carbon footprint (cradle-to-gate); hot-spot identification; CBAM compliance process; reduction targets set',
         'CBAM-compliant carbon accounting (verified); carbon labels on products; Scope 3 tracking started; carbon reduction 20%+',
         'Carbon-negative potential; carbon data as service to customers; industry carbon benchmark; carbon as competitive advantage'),
        ('G03', 'Waste Reduction & Circularity', 0.08,
         'High waste output; no recycling program; scrap treated as cost of doing business; linear economy',
         'Basic waste segregation; recycling for valuable scrap (steel, aluminum); waste reduction targets; scrap rate 5-8%',
         'Waste reduction Kaizen; circular economy pilots (cutting fluid recycling, mold reuse); scrap rate <3%',
         'Closed-loop material flows; industrial symbiosis with nearby companies; scrap <1%; waste-to-energy for non-recyclables',
         'Zero-waste manufacturing; full circularity; all by-products valorized; waste elimination as culture'),
        ('G04', 'Environmental Management System', 0.08,
         'Non-compliance issues; no environmental management system; regulatory risks unmanaged',
         'Basic compliance (emissions/wastewater/noise); environmental KPIs tracked; corrective actions managed',
         'ISO 14001 certified; proactive environmental management; beyond compliance; environmental improvement roadmap',
         'Integrated ESG reporting (GRI/SASB); environmental excellence; green supply chain requirements for suppliers',
         'Environmental leadership; regenerative operations; industry sustainability benchmark; environmental stewardship culture'),
        ('G05', 'Green Product Design (DfE)', 0.07,
         'No environmental consideration in product design; material selection based on cost/performance only',
         'Basic Design for Environment (DfE) awareness; material substitution considerations; recyclability review',
         'LCA for key products; eco-design guidelines; green material selection; design for disassembly considered',
         'Full product LCA; eco-innovation pipeline; green product portfolio; environmental product declarations (EPD)',
         'Cradle-to-cradle design; green product differentiation; sustainability as brand; circular product design standard'),
        ('G06', 'Green Supply Chain & Procurement', 0.06,
         'No supplier environmental requirements; no green procurement policy; logistics optimization not considered',
         'Basic supplier environmental screening; green procurement policy drafted; transportation efficiency review',
         'Supplier carbon data collection; green procurement active; logistics optimization (route, load); packaging reduction',
         'Scope 3 reduction programs; supplier carbon coaching; green logistics (EV fleet, rail); sustainable packaging',
         'Carbon-neutral supply chain; ecosystem-level sustainability; green value network; supplier sustainability scorecards'),
        ('G07', 'Water & Resource Management', 0.06,
         'No water tracking; high consumption; wastewater untreated; resource efficiency not measured',
         'Water metering started; basic consumption targets; wastewater treatment compliant; resource tracking begun',
         'Water recycling programs; process-level water monitoring; consumption reduced 20%+; zero liquid discharge pilots',
         'Closed-loop water systems; AI-optimized water usage; rainwater harvesting; water-positive operations',
         'Water stewardship; industry-leading water efficiency; water risk management; community water partnership'),
        ('G08', 'Renewable Energy Adoption', 0.06,
         'No renewable energy; 100% grid/fossil; no carbon offset; energy source not a consideration',
         'Renewable energy assessment; solar feasibility study; green energy certificates purchased partially',
         'On-site solar/wind installation; renewable energy >20% of total; power purchase agreements (PPA) active',
         'Renewable energy >50%; battery storage; microgrid capability; energy independence strategy',
         '100% renewable energy; energy-positive; grid services revenue; renewable energy as competitive advantage'),
        ('G09', 'Packaging & Logistics Optimization', 0.06,
         'Excessive packaging; single-use materials; no returnable packaging; logistics not optimized',
         'Packaging reduction started; returnable packaging piloted for key customers; logistics efficiency review',
         'Sustainable packaging standard; returnable packaging for 50%+ of shipments; route optimization; load efficiency >85%',
         'Circular packaging system; AI-optimized logistics; carbon-neutral last-mile delivery; packaging as service',
         'Zero-waste packaging; autonomous logistics optimization; packaging innovation as differentiator'),
        ('G10', 'Employee Green Engagement', 0.05,
         'No environmental awareness training; employees do not understand sustainability; no green culture',
         'Basic environmental awareness training; green team formed; suggestion program includes environmental ideas',
         'Green Kaizen events; employee-led sustainability projects; environmental metrics visible; green culture growing',
         'Sustainability embedded in performance goals; employee green innovation program; cross-functional green teams',
         'Sustainability culture at all levels; every employee is environmental champion; green innovation as norm'),
        ('G11', 'Regulatory Compliance & ESG Reporting', 0.05,
         'Reactive compliance; no ESG reporting; regulatory risks not tracked; no stakeholder communication',
         'Compliance tracking system; basic ESG data collection; regulatory change monitoring; annual sustainability summary',
         'Proactive compliance management; ESG report published annually; GRI/SASB alignment; stakeholder engagement',
         'Integrated ESG reporting; ESG ratings achieved; investor-grade ESG data; sustainability-linked financing',
         'ESG leadership; industry benchmark reporting; ESG as strategic driver; transparent stakeholder communication'),
        ('G12', 'Biodiversity & Land Use', 0.05,
         'No biodiversity consideration; land use not assessed; no environmental impact assessment',
         'Basic environmental impact assessment; biodiversity awareness; land use efficiency review',
         'Biodiversity action plan; green infrastructure on site; land use optimization; ecological footprint measured',
         'Net-positive biodiversity; ecological restoration projects; sustainable land management; nature-based solutions',
         'Biodiversity leadership; ecosystem services valued; regenerative land use; industry biodiversity benchmark'),
    ]

    # ============================================================
    # RESILIENCE (R) - 12 items
    # ============================================================
    r_items = [
        ('R01', 'Supply Risk Management & Dual-Sourcing', 0.10,
         'Single-source for key materials; no risk assessment; reactive to disruptions; no contingency plans',
         'Risk register started; safety stock for top-10 items; basic contingency; annual supplier risk review',
         'Dual-source >80% of critical materials; supplier risk scoring; scenario planning; 7-day strategic buffer',
         'AI supply risk monitoring; dynamic buffering; stress-test program; dual-source 100% for critical items',
         'Self-healing supply network; AI-adaptive sourcing; resilience as competitive advantage; ecosystem risk management'),
        ('R02', 'Business Continuity & Crisis Management', 0.09,
         'No BCP; single-point-of-failures common; long recovery time (>1 week); no crisis team',
         'Basic BCP drafted; key process redundancy planned; emergency response SOP; crisis team identified',
         'BCP tested & updated annually; alternative production plans; recovery <48h; crisis simulation exercises',
         'Digital twin for continuity planning; auto-failover for critical systems; recovery <8h; continuous BCP improvement',
         'Self-reconfiguring operations; zero-disruption target; resilience testing as culture; antifragile operations'),
        ('R03', 'Demand Flexibility & Responsiveness', 0.08,
         'Rigid production; long changeover; cannot absorb demand swings >20%; no demand sensing',
         'SMED started; flexibility improvement; some demand buffering; basic demand forecasting',
         'Quick changeover (<15min); flexible capacity (+/-20%); demand sensing; collaborative planning with key customers',
         'AI-driven demand forecasting; flexible automation; dynamic capacity allocation; mass customization capability',
         'Autonomous demand-response; reconfigurable manufacturing; zero-delay response; demand shaping capability'),
        ('R04', 'Cybersecurity & IT Resilience', 0.08,
         'No cybersecurity measures; no data backup strategy; high vulnerability; IT downtime impacts production',
         'Basic firewall & antivirus; regular backups; IT security policy; access controls; some OT awareness',
         'IEC 62443 compliance; OT/IT segmentation; incident response team; tested disaster recovery; <4h recovery',
         'Zero-trust architecture; AI threat detection; cyber resilience testing; <1h recovery; security operations center',
         'Self-healing IT/OT; quantum-ready security; cyber resilience benchmark; security as competitive advantage'),
        ('R05', 'Organizational Resilience & Agility', 0.08,
         'Rigid hierarchy; slow decision-making (>1 week for strategic decisions); crisis paralysis; no empowerment',
         'Crisis communication plan; cross-functional response team; basic delegation; some agile practices',
         'Rapid decision protocols (<24h strategic); decentralized authority; learning from disruptions; agile at scale',
         'Anticipatory organization; scenario-based leadership; resilience culture embedded; self-organizing teams',
         'Adaptive organization; thrives on disruption; antifragile operations; organizational evolution as capability'),
        ('R06', 'Financial Resilience', 0.07,
         'Thin margins; no reserves; one disruption away from crisis; no financial risk management',
         'Cash reserve policy; basic financial risk management; insurance coverage; financial KPI monitoring',
         'Diversified revenue streams; stress-tested financials; hedging strategies; financial early warning system',
         'Dynamic financial modeling; real-time risk-adjusted pricing; AI treasury management; scenario planning',
         'Financially antifragile; disruption creates opportunity; strategic reserves; financial agility as advantage'),
        ('R07', 'Production Flexibility & Redundancy', 0.07,
         'No production redundancy; single-line dependency; no alternative routing; capacity rigidity',
         'Basic redundancy for bottleneck equipment; alternative routing identified; overtime/flex capacity available',
         'Flexible manufacturing system; multiple production lines for key products; cross-trained workforce; surge capacity 20%',
         'Reconfigurable production; mobile manufacturing units; AI-optimized production routing; surge capacity 50%',
         'Fully flexible production; network manufacturing; zero single-point-of-failure; production as a service'),
        ('R08', 'Supplier Relationship Resilience', 0.07,
         'Transactional supplier relationships; no trust; price-only focus; no joint risk management',
         'Key supplier partnerships; regular communication; joint planning for demand; shared forecasts',
         'Strategic supplier alliances; joint risk management; co-investment in capacity; transparent cost structures',
         'Supplier ecosystem development; supplier resilience programs; shared digital platforms; collaborative innovation',
         'Resilient supply ecosystem; mutual dependency management; supplier as extension of enterprise; co-evolution'),
        ('R09', 'Information & Data Resilience', 0.06,
         'Single data center; no backup; data loss risk high; no data recovery plan; manual data processes',
         'Basic data backup; secondary data center or cloud backup; data recovery tested; critical data identified',
         'Real-time data replication; automated failover; data integrity monitoring; data governance enforced',
         'Distributed data architecture; AI-assisted data quality; blockchain for critical data; zero data loss tolerance',
         'Self-healing data infrastructure; autonomous data management; data resilience as competitive advantage'),
        ('R10', 'Workforce Resilience & Cross-Training', 0.06,
         'Single-skill operators; no cross-training; high dependency on key individuals; knowledge silos',
         'Basic cross-training started; skill matrix created; <30% multi-skilled; key person risk identified',
         'Cross-training program active; multi-skill >50%; knowledge management system; succession planning',
         'T-shaped talent program; multi-skill >70%; AI-assisted skill development; workforce planning analytics',
         'Fully resilient workforce; everyone cross-trained; knowledge as organizational asset; workforce as advantage'),
        ('R11', 'Geopolitical & Market Risk', 0.06,
         'No geopolitical risk assessment; single market dependency; no scenario planning for trade disruption',
         'Basic geopolitical awareness; market diversification started; trade compliance program; some scenario analysis',
         'Geopolitical risk monitoring; diversified markets (>3 regions); trade compliance expertise; scenario plans active',
         'AI-powered geopolitical risk intelligence; dynamic market entry/exit; regulatory change prediction; hedging strategies',
         'Geopolitical agility; multi-regional operations; trade as strategic weapon; market risk as opportunity'),
        ('R12', 'Learning from Disruptions', 0.05,
         'No post-incident review; same disruptions recur; no knowledge capture; blame culture',
         'Basic incident review process; A3 for major disruptions; lessons documented; some corrective actions tracked',
         'Structured post-incident review (all levels); knowledge management system; corrective action verification; learning culture',
         'AI-assisted incident analysis; pattern recognition across disruptions; predictive risk indicators; organizational learning loop',
         'Learning organization; disruptions drive improvement; antifragile learning; industry resilience knowledge sharing'),
    ]

    # ============================================================
    # HUMAN-CENTRIC (H) - 12 items
    # ============================================================
    h_items = [
        ('H01', 'Employee Participation & Engagement', 0.09,
         'Top-down only; employees follow orders; no suggestion system; engagement score unknown',
         'Suggestion box exists; <10% participation; basic team meetings; annual engagement survey',
         'Kaizen suggestion system active; 30-50% participation; team-based improvement; monthly engagement pulse',
         'Employee-led Kaizen; >70% participation; autonomous improvement teams; engagement score >75%',
         'Self-organizing improvement; 90%+ participation; innovation from everyone; employer of choice'),
        ('H02', 'Skill Development & Multi-Skilling', 0.09,
         'Single-skill operators; no training plan; skill gaps unaddressed; no career development',
         'Basic training plan; multi-skill training started; <30% multi-skilled; annual training hours tracked',
         'Skill matrix active; multi-skill >50%; structured training with assessment; digital literacy program',
         'T-shaped talent program; multi-skill >70%; data literacy for all; AI upskilling; career pathing',
         'Continuous learning organization; self-directed development; skill innovation lab; workforce as talent magnet'),
        ('H03', 'Workplace Wellbeing & Safety Culture', 0.08,
         'Ergonomics ignored; safety compliance only; high turnover/stress; wellbeing not a priority',
         'Basic ergonomics assessment; safety programs; employee satisfaction survey; EAP available',
         'Ergonomic improvements active; wellness programs; psychological safety initiatives; LTIR below industry average',
         'Human-centric workplace design; AI-augmented ergonomics; proactive wellbeing; turnover <5%',
         'Workplace as talent magnet; optimal human performance; wellbeing as culture; industry benchmark'),
        ('H04', 'Empowerment & Decision Authority', 0.08,
         'All decisions from management; no frontline authority; strict hierarchy; slow response',
         'Some delegation to supervisors; basic decision authority at team lead level; Andon pull authority',
         'Team-based decision making; self-managed work cells; employee authority for quality decisions; decentralized',
         'Employee autonomy in process improvement; AI-human decision partnership; distributed authority; self-governance',
         'Self-governing teams; human-AI symbiosis; distributed decision authority; empowerment as culture'),
        ('H05', 'Innovation Culture & Intrapreneurship', 0.07,
         'No innovation; management dictates all changes; fear of failure; no experimentation',
         'Innovation suggestion program; occasional improvement workshops; some tolerance for experimentation',
         'Structured innovation process; Kaizen events; cross-functional innovation teams; rapid prototyping capability',
         'Innovation labs; employee-driven digital innovation; hackathons; innovation time allocation (10%+)',
         'Continuous innovation engine; breakthrough thinking norm; innovation ecosystem; intrapreneurship as career path'),
        ('H06', 'Meaningful Work & Purpose', 0.06,
         'Work as pure task execution; no connection to purpose; no job enrichment; monotony',
         'Basic communication of company mission; some job enrichment; team purpose defined; recognition program',
         'Clear line-of-sight to customer value; job rotation; skill variety; contribution visibility; purpose workshops',
         'Purpose-driven work; autonomy+mastery+purpose framework; human potential development; job crafting',
         'Work as self-actualization; human flourishing; industry employer-of-choice; purpose as strategy'),
        ('H07', 'Diversity, Equity & Inclusion', 0.06,
         'No DEI program; homogeneous workforce; no diversity metrics; unconscious bias unaddressed',
         'Basic DEI policy; diversity metrics tracked; bias awareness training; employee resource groups started',
         'DEI strategy active; diverse hiring practices; inclusive leadership training; pay equity analysis; belonging surveys',
         'DEI embedded in culture; diverse leadership pipeline; supplier diversity program; accessibility excellence',
         'DEI leadership; industry benchmark; inclusive innovation; diversity as competitive advantage'),
        ('H08', 'Communication & Transparency', 0.06,
         'Information hoarded; top-down communication only; no feedback mechanism; low trust',
         'Regular town halls; suggestion system; basic feedback channels; some transparency on company performance',
         'Multi-directional communication; transparent strategy sharing; regular feedback (upward/downward); trust-building',
         'Radical transparency; real-time information access; AI-assisted communication; trust as culture',
         'Open communication culture; information as right; transparent decision-making; trust as competitive advantage'),
        ('H09', 'Recognition & Reward Systems', 0.06,
         'No formal recognition; only financial rewards; no peer recognition; achievement invisible',
         'Basic recognition program; annual awards; some peer recognition; performance-based bonuses',
         'Multi-level recognition (peer/manager/executive); spot awards; skill-based pay; non-monetary recognition',
         'Real-time recognition platform; AI-assisted fair rewards; career development as reward; recognition culture',
         'Holistic reward system; recognition as culture; personalized rewards; total rewards optimization'),
        ('H10', 'Leadership Development', 0.06,
         'No leadership development; managers appointed by seniority; no coaching; command-and-control style',
         'Basic leadership training; some coaching; 360 feedback for managers; leadership competency model',
         'Leadership development pipeline; coaching culture; servant leadership; succession planning; high-potential programs',
         'Leadership as practice; continuous leader development; AI-assisted coaching; leadership bench strength',
         'Leadership excellence; industry leadership pipeline; leadership as organizational capability; leader brand'),
        ('H11', 'Digital Skills & AI Literacy', 0.06,
         'No digital skills program; workforce unprepared for digital tools; AI fear; digital divide',
         'Basic digital literacy training; some online learning; digital champions program; tool-specific training',
         'Digital skills framework; AI literacy for all levels; blended learning; digital mentorship; upskilling roadmap',
         'Digital fluency as core competency; AI-human collaboration skills; continuous digital learning; digital career paths',
         'AI-native workforce; digital skills as hiring criterion; continuous digital evolution; digital talent ecosystem'),
        ('H12', 'Change Management Capability', 0.05,
         'No change management; changes imposed; resistance high; transformation failures common',
         'Basic change management awareness; communication during changes; some stakeholder engagement; training on new processes',
         'Change management framework; stakeholder analysis; resistance management; change agents network; ADKAR model',
         'Change as capability; organizational agility; AI-assisted change impact analysis; continuous transformation readiness',
         'Change mastery; organizational evolution as norm; antifragile change culture; transformation as competitive advantage'),
    ]

    all_items = [
        ('O', o_items),
        ('D', d_items),
        ('G', g_items),
        ('R', r_items),
        ('H', h_items),
    ]

    total = 0
    for dim_code, items in all_items:
        for i, (item_code, item_name, weight, l1, l2, l3, l4, l5) in enumerate(items):
            c.execute("""
                INSERT INTO lean20_checklist_items
                (dimension_code, item_code, item_name, item_weight, l1_desc, l2_desc, l3_desc, l4_desc, l5_desc, sort_order)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (dim_code, item_code, item_name, weight, l1, l2, l3, l4, l5, i + 1))
            total += 1

    conn.commit()

    # Verify
    print(f"Inserted {total} checklist items")
    for dim_code in ['O', 'D', 'G', 'R', 'H']:
        count = c.execute("SELECT COUNT(*) FROM lean20_checklist_items WHERE dimension_code=?", (dim_code,)).fetchone()[0]
        print(f"  {dim_code}: {count} items")

    # Validate total weight per dimension
    print("\nWeight distribution:")
    for dim_code in ['O', 'D', 'G', 'R', 'H']:
        total_w = c.execute("SELECT SUM(item_weight) FROM lean20_checklist_items WHERE dimension_code=?", (dim_code,)).fetchone()[0]
        print(f"  {dim_code}: {total_w:.2f}")

    conn.close()
    print("\nDeep checklist migration complete!")

if __name__ == '__main__':
    migrate()
